# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3788888dac4891eb7a34bdb263dfca002da510fec4704ee5be42dd5c3fe9ab5e2b0393eae0bef9466359e3be173f484c383ec16ac3bb6ec3b76b6365ecb2c3e

test:
  secret_key_base: b1f977d7d42773a6d1af883988ba62944668947cf5713fdcb340f2839265d4bcd73ca33df002bee1dcf4d074051129a8f4a6b4682fb9ebc3288835de3c5a8341

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
